# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8d886ba4bb02d514e23c2f3d37b8cb59"
name = "scopes-tuts-2025-08"
handle = "scopes-tuts-2025-08"
application_url = "https://timothy-implied-breeds-mrna.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ "write_products" ]

[auth]
redirect_urls = [
  "https://timothy-implied-breeds-mrna.trycloudflare.com/auth/callback",
  "https://timothy-implied-breeds-mrna.trycloudflare.com/auth/shopify/callback",
  "https://timothy-implied-breeds-mrna.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
